version: '3.8'

services:
  formatho:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: formatho
    restart: unless-stopped
    environment:
      - NODE_ENV=production
