name: Deploy to DigitalOcean (No Registry)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: formatho

jobs:
  build-and-transfer:
    runs-on: ubuntu-latest
    environment: digital_ocean_formatho
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Save Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker save ${{ env.IMAGE_NAME }}:latest | gzip > ${{ env.IMAGE_NAME }}.tar.gz

      - name: Copy Files to Droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "${{ env.IMAGE_NAME }}.tar.gz,docker-compose.yml"
          target: "/home/${{ secrets.DO_USERNAME }}/formatho"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /home/${{ secrets.DO_USERNAME }}/formatho
            gunzip -c ${{ env.IMAGE_NAME }}.tar.gz | docker load
            docker-compose up -d
            rm ${{ env.IMAGE_NAME }}.tar.gz
            docker image prune -f
